In [1]:
from sklearn.datasets import load_iris
iris = load_iris()
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)

In [3]:
df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [4]:
df['target'] = iris.target

In [5]:
df['target_names'] = df.target.apply(lambda x: iris.target_names[x])

In [20]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

In [27]:
x = df.drop(['target', 'target_names'], axis = 'columns')
y = df.target
from sklearn.model_selection import train_test_split

In [68]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 100)

In [69]:
model = KNeighborsClassifier(n_neighbors=3)

In [70]:
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [72]:
model.score(x_test, y_test)

1.0

In [87]:
y_pred = model.predict(x_test)
y_pred

array([2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 2, 2, 0,
       2, 0, 1, 2, 1, 0, 1, 2])

In [86]:
y_test.values

array([2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 2, 2, 0,
       2, 0, 1, 2, 1, 0, 1, 2])

In [107]:
import numpy as np
predicted = np.array([y_test.values, y_pred])
predicted

array([[2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 2, 2, 0,
        2, 0, 1, 2, 1, 0, 1, 2],
       [2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 2, 2, 0,
        2, 0, 1, 2, 1, 0, 1, 2]])

In [108]:
pred_df = pd.DataFrame(predicted.T, columns = ['Actual', 'Predicted'])
pred_df

Actual  Predicted
0        2          2
1        0          0
2        2          2
3        0          0
4        2          2
5        2          2
6        0          0
7        0          0
8        2          2
9        0          0
10       0          0
11       2          2
12       0          0
13       0          0
14       2          2
15       1          1
16       1          1
17       1          1
18       2          2
19       2          2
20       2          2
21       0          0
22       2          2
23       0          0
24       1          1
25       2          2
26       1          1
27       0          0
28       1          1
29       2          2

if u get error related to shape of array while converting arrays of dataframe, just use Transpose method: array.T